# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
# << macros

Name:       xorg-x11-proto-xf86vidmodeproto
Summary:    X.Org X11 Protocol xf86vidmodeproto
Version:    2.3.1
Release:    0
Group:      Development/System
License:    MIT
URL:        http://www.x.org
Source0:    http://xorg.freedesktop.org/releases/individual/proto/xf86vidmodeproto-%{version}.tar.bz2
Source100:  xorg-x11-proto-xf86vidmodeproto.yaml
Provides:   xf86vidmodeproto


%description
This extension defines a protocol for dynamically configuring modelines and gamma




%prep
%setup -q -n xf86vidmodeproto-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static \
    --libdir=%{_datadir}

make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post






%files
%defattr(-,root,root,-)
# >> files
%{_datadir}/pkgconfig/xf86vidmodeproto.pc
%{_includedir}/X11/extensions/xf86vmstr.h
%{_includedir}/X11/extensions/xf86vm.h
%{_includedir}/X11/extensions/xf86vmproto.h
# << files


